// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADtbiZuo2SYwEPE6CR-xWceIfOoslPdzI',
    appId: '1:481649968102:web:45f0a774b6a72e749e8c27',
    messagingSenderId: '481649968102',
    projectId: 'quizapp-ym',
    authDomain: 'quizapp-ym.firebaseapp.com',
    storageBucket: 'quizapp-ym.appspot.com',
    measurementId: 'G-TDWPY979XK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACtfblDH11tUS71PMfV6A4SSNAph_Cd08',
    appId: '1:481649968102:android:071fc6c51c4ee6479e8c27',
    messagingSenderId: '481649968102',
    projectId: 'quizapp-ym',
    storageBucket: 'quizapp-ym.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMCfzK39LkHdpJL4ZbKIZMCRSHDrbTG7U',
    appId: '1:481649968102:ios:559712f11dafb7d69e8c27',
    messagingSenderId: '481649968102',
    projectId: 'quizapp-ym',
    storageBucket: 'quizapp-ym.appspot.com',
    iosClientId: '481649968102-v4ubhtfrckn23nc6el2m62p01vigg2pb.apps.googleusercontent.com',
    iosBundleId: 'com.example.quizApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMCfzK39LkHdpJL4ZbKIZMCRSHDrbTG7U',
    appId: '1:481649968102:ios:559712f11dafb7d69e8c27',
    messagingSenderId: '481649968102',
    projectId: 'quizapp-ym',
    storageBucket: 'quizapp-ym.appspot.com',
    iosClientId: '481649968102-v4ubhtfrckn23nc6el2m62p01vigg2pb.apps.googleusercontent.com',
    iosBundleId: 'com.example.quizApp',
  );
}
